### ISSUE TITLE
arc-vr-phys problem with right hand colliders

### ISSUE THREAD

**Issue by Helliaca** [MPIB/arc-vr#5]
> the physical hands and the hand colliders are working properly for the left hand but not for the right hand it seems like you cant even grab with the right hand.

**Comment by wmcnamara** [comment]
Is this still an issue that ACR VR is facing? I can grab using my right hand on my own machine as of now

**Comment by Helliaca** [comment]
You're right. There was a problem with the negatively scaled colliders on the right hand at some point, but I can't seem to replicate the issue either anymore.
